# Generated by Django 4.2.4 on 2023-09-20 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 17, 56, 30, 116913)),
        ),
    ]
